#!/usr/bin/env python3
"""Generate spin-orbital CCSDT residual equations with Wick&d.

Usage:
    WICKED_PATH=/private/tmp/wicked /usr/bin/python3 tools/generate_ccsdt_wicked.py
    WICKED_PATH=/private/tmp/wicked /usr/bin/python3 tools/generate_ccsdt_wicked.py --summary

The Julia implementation in src/ccsdt.jl is a direct translation of this
generated einsum form.
"""

from __future__ import annotations

import argparse
import os
import sys
import time


def import_wicked():
    wicked_path = os.environ.get("WICKED_PATH")
    if wicked_path:
        sys.path.insert(0, wicked_path)
    try:
        import wicked as w
    except ModuleNotFoundError as exc:
        raise SystemExit(
            "Could not import wicked. Set WICKED_PATH to a built Wicked checkout "
            "or install Wicked into this Python environment."
        ) from exc
    return w


def generate_equation(mbeq, nocc: int, nvir: int) -> str:
    res_sym = f"R{'o' * nocc}{'v' * nvir}"
    code = [
        f"def evaluate_residual_{nocc}_{nvir}(H, T):",
        "    # contributions to the residual",
    ]
    if nocc + nvir == 0:
        code.append("    R = 0.0")
    else:
        dims = ",".join(["nocc"] * nocc + ["nvir"] * nvir)
        code.append(f"    {res_sym} = np.zeros(({dims}))")

    for eq in mbeq["o" * nocc + "|" + "v" * nvir]:
        code.append(f"    {eq.compile('einsum')}")

    code.append(f"    return {res_sym}")
    return "\n".join(code)


def build_ccsdt_equations(w):
    w.reset_space()
    w.add_space("o", "fermion", "occupied", ["i", "j", "k", "l", "m", "n"])
    w.add_space("v", "fermion", "unoccupied", ["a", "b", "c", "d", "e", "f"])

    cluster = w.op("T", ["v+ o", "v+ v+ o o", "v+ v+ v+ o o o"])
    hamiltonian = w.utils.gen_op("H", 1, "ov", "ov") + w.utils.gen_op("H", 2, "ov", "ov")
    hbar = w.bch_series(hamiltonian, cluster, 4)
    expr = w.WickTheorem().contract(w.rational(1), hbar, 0, 6)
    return expr.to_manybody_equation("R")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--summary", action="store_true", help="print equation counts only")
    args = parser.parse_args()

    w = import_wicked()
    start = time.perf_counter()
    mbeq = build_ccsdt_equations(w)
    elapsed = time.perf_counter() - start

    if args.summary:
        print(f"generation_seconds {elapsed:.3f}")
        for rank in range(4):
            key = "o" * rank + "|" + "v" * rank
            code = generate_equation(mbeq, rank, rank)
            print(
                f"{key or '|'} terms {len(mbeq[key])} "
                f"code_lines {len(code.splitlines())} chars {len(code)}"
            )
        return 0

    print("# Generated by tools/generate_ccsdt_wicked.py")
    print("# Requires: import numpy as np, nocc, nvir")
    for rank in range(4):
        print()
        print(f"# ---- residual rank {rank} ----")
        print(generate_equation(mbeq, rank, rank))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
