"""
Full spin-orbital CCSDT from Wicked-generated residual equations.

Project #20 solves the connected singles, doubles, and triples amplitude
equations.  The residual contractions below follow the spin-orbital CCSDT
equations generated by Wick&d:

https://github.com/fevangelista/wicked

The determinant-space CISDT helpers remain in this file as a compact reference
for determinant labels and CI-to-CC amplitude conversion.
"""

using LinearAlgebra, Printf, Einsum
using Base.Threads: @threads, maxthreadid, threadid

function _ccsdt_hamiltonian_blocks(aso, F_so, o, v, nofe)
    oi = 1:o
    vi = (nofe + 1):(nofe + v)
    return (
        oo = F_so[oi, oi],
        ov = F_so[oi, vi],
        vo = F_so[vi, oi],
        vv = F_so[vi, vi],
        oooo = aso[oi, oi, oi, oi],
        ooov = aso[oi, oi, oi, vi],
        oovv = aso[oi, oi, vi, vi],
        ovoo = aso[oi, vi, oi, oi],
        ovov = aso[oi, vi, oi, vi],
        ovvv = aso[oi, vi, vi, vi],
        vvoo = aso[vi, vi, oi, oi],
        vvov = aso[vi, vi, oi, vi],
        vvvv = aso[vi, vi, vi, vi],
    )
end

"""
    ccsdt_energy(H, t1, t2)

Evaluate the CCSDT correlation energy from Wicked's spin-orbital energy
equation.  Triples enter the energy indirectly through the converged `t1/t2`.

```text
E_CCSDT = sum_ia f_ai t_i^a
        + 1/4 sum_ijab <ab||ij> t_ij^ab
        + 1/2 sum_ijab <ab||ij> t_i^a t_j^b.
```
"""
function ccsdt_energy(H, t1, t2)
    o, v = size(t1)
    partial = zeros(Float64, maxthreadid())
    @threads for idx in eachindex(t1)
        x = idx - 1
        i = (x % o) + 1
        a = (x ÷ o) + 1
        @inbounds partial[threadid()] += H.vo[a,i] * t1[i,a]
    end

    @threads for idx in eachindex(t2)
        x = idx - 1
        i = (x % o) + 1; x ÷= o
        j = (x % o) + 1; x ÷= o
        a = (x % v) + 1; x ÷= v
        b = (x % v) + 1
        @inbounds partial[threadid()] += (
            0.25 * H.vvoo[a,b,i,j] * t2[i,j,a,b] +
            0.5  * H.vvoo[a,b,i,j] * t1[j,b] * t1[i,a]
        )
    end
    return sum(partial)
end

"""
    ccsdt_residuals(H, t1, t2, t3)

Evaluate the unantisymmetrized Wicked-generated CCSDT residual equations for
`T1`, `T2`, and `T3`.  The residuals are projections of the similarity
transformed Hamiltonian,

```text
R_i^a       = <Phi_i^a| exp(-T) H exp(T) |Phi_0>
R_ij^ab     = <Phi_ij^ab| exp(-T) H exp(T) |Phi_0>
R_ijk^abc   = <Phi_ijk^abc| exp(-T) H exp(T) |Phi_0>,
```

with `T = T1 + T2 + T3`.
"""
function ccsdt_residuals(H, t1, t2, t3)
    o, v = size(t1)
    H_oo = H.oo;     H_ov = H.ov;     H_vo = H.vo;     H_vv = H.vv
    H_oooo = H.oooo; H_ooov = H.ooov; H_oovv = H.oovv
    H_ovoo = H.ovoo; H_ovov = H.ovov; H_ovvv = H.ovvv
    H_vvoo = H.vvoo; H_vvov = H.vvov; H_vvvv = H.vvvv

    R1 = zeros(Float64, o, v)
    tmp1 = zeros(Float64, o, v)

    @einsum tmp1[i,a] = H_oo[i,j] * t1[j,a]
    R1 .-= tmp1
    @einsum tmp1[i,a] = H_vo[b,j] * t1[j,a] * t1[i,b]
    R1 .-= tmp1
    @einsum tmp1[i,a] = H_vo[b,j] * t2[i,j,a,b]
    R1 .+= tmp1
    @einsum tmp1[i,a] = H_ovoo[i,b,j,k] * t1[k,a] * t1[j,b]
    R1 .+= tmp1
    @einsum tmp1[i,a] = H_ovoo[i,b,j,k] * t2[j,k,a,b]
    R1 .-= 0.5 .* tmp1
    @einsum tmp1[i,a] = H_vvoo[b,c,j,k] * t1[j,a] * t2[i,k,b,c]
    R1 .-= 0.5 .* tmp1
    @einsum tmp1[i,a] = H_vvoo[b,c,j,k] * t1[k,a] * t1[i,c] * t1[j,b]
    R1 .-= tmp1
    @einsum tmp1[i,a] = H_vvoo[b,c,j,k] * t3[i,j,k,a,b,c]
    R1 .+= 0.25 .* tmp1
    @einsum tmp1[i,a] = H_vvoo[b,c,j,k] * t1[i,b] * t2[j,k,a,c]
    R1 .-= 0.5 .* tmp1
    @einsum tmp1[i,a] = H_vvoo[b,c,j,k] * t1[j,b] * t2[i,k,a,c]
    R1 .+= tmp1
    @einsum tmp1[i,a] = H_ovov[i,b,j,a] * t1[j,b]
    R1 .-= tmp1
    @einsum tmp1[i,a] = H_vvov[b,c,j,a] * t2[i,j,b,c]
    R1 .-= 0.5 .* tmp1
    @einsum tmp1[i,a] = H_vvov[b,c,j,a] * t1[i,c] * t1[j,b]
    R1 .+= tmp1
    R1 .+= H_ov
    @einsum tmp1[i,a] = H_vv[b,a] * t1[i,b]
    R1 .+= tmp1

    R2 = zeros(Float64, o, o, v, v)
    tmp2 = zeros(Float64, o, o, v, v)

    @einsum tmp2[i,j,a,b] = H_oo[i,k] * t2[j,k,a,b]
    R2 .+= 0.5 .* tmp2
    @einsum tmp2[i,j,a,b] = H_vo[c,k] * t1[k,a] * t2[i,j,b,c]
    R2 .+= 0.5 .* tmp2
    @einsum tmp2[i,j,a,b] = H_vo[c,k] * t3[i,j,k,a,b,c]
    R2 .+= 0.25 .* tmp2
    @einsum tmp2[i,j,a,b] = H_vo[c,k] * t1[i,c] * t2[j,k,a,b]
    R2 .+= 0.5 .* tmp2
    @einsum tmp2[i,j,a,b] = H_oooo[i,j,k,l] * t1[k,a] * t1[l,b]
    R2 .+= 0.25 .* tmp2
    @einsum tmp2[i,j,a,b] = H_oooo[i,j,k,l] * t2[k,l,a,b]
    R2 .+= 0.125 .* tmp2
    @einsum tmp2[i,j,a,b] = H_ovoo[i,c,k,l] * t1[k,a] * t1[l,b] * t1[j,c]
    R2 .+= 0.5 .* tmp2
    @einsum tmp2[i,j,a,b] = H_ovoo[i,c,k,l] * t1[k,a] * t2[j,l,b,c]
    R2 .-= tmp2
    @einsum tmp2[i,j,a,b] = H_ovoo[i,c,k,l] * t3[j,k,l,a,b,c]
    R2 .+= 0.25 .* tmp2
    @einsum tmp2[i,j,a,b] = H_ovoo[i,c,k,l] * t1[j,c] * t2[k,l,a,b]
    R2 .+= 0.25 .* tmp2
    @einsum tmp2[i,j,a,b] = H_ovoo[i,c,k,l] * t1[k,c] * t2[j,l,a,b]
    R2 .-= 0.5 .* tmp2
    @einsum tmp2[i,j,a,b] = H_vvoo[c,d,k,l] * t1[k,a] * t1[l,b] * t2[i,j,c,d]
    R2 .+= 0.125 .* tmp2
    @einsum tmp2[i,j,a,b] = H_vvoo[c,d,k,l] * t1[k,a] * t1[l,b] * t1[i,d] * t1[j,c]
    R2 .-= 0.25 .* tmp2
    @einsum tmp2[i,j,a,b] = H_vvoo[c,d,k,l] * t1[k,a] * t3[i,j,l,b,c,d]
    R2 .+= 0.25 .* tmp2
    @einsum tmp2[i,j,a,b] = H_vvoo[c,d,k,l] * t1[k,a] * t1[i,c] * t2[j,l,b,d]
    R2 .-= tmp2
    @einsum tmp2[i,j,a,b] = H_vvoo[c,d,k,l] * t1[l,a] * t1[k,c] * t2[i,j,b,d]
    R2 .+= 0.5 .* tmp2
    @einsum tmp2[i,j,a,b] = H_vvoo[c,d,k,l] * t2[i,l,a,b] * t2[j,k,c,d]
    R2 .+= 0.25 .* tmp2
    @einsum tmp2[i,j,a,b] = H_vvoo[c,d,k,l] * t2[k,l,a,b] * t2[i,j,c,d]
    R2 .+= 0.0625 .* tmp2
    @einsum tmp2[i,j,a,b] = H_vvoo[c,d,k,l] * t2[i,j,a,d] * t2[k,l,b,c]
    R2 .+= 0.25 .* tmp2
    @einsum tmp2[i,j,a,b] = H_vvoo[c,d,k,l] * t2[i,l,a,d] * t2[j,k,b,c]
    R2 .+= 0.5 .* tmp2
    @einsum tmp2[i,j,a,b] = H_vvoo[c,d,k,l] * t1[i,c] * t3[j,k,l,a,b,d]
    R2 .+= 0.25 .* tmp2
    @einsum tmp2[i,j,a,b] = H_vvoo[c,d,k,l] * t1[k,c] * t3[i,j,l,a,b,d]
    R2 .+= 0.25 .* tmp2
    @einsum tmp2[i,j,a,b] = H_vvoo[c,d,k,l] * t1[i,d] * t1[j,c] * t2[k,l,a,b]
    R2 .-= 0.125 .* tmp2
    @einsum tmp2[i,j,a,b] = H_vvoo[c,d,k,l] * t1[i,d] * t1[k,c] * t2[j,l,a,b]
    R2 .+= 0.5 .* tmp2
    @einsum tmp2[i,j,a,b] = H_ooov[i,j,k,a] * t1[k,b]
    R2 .+= 0.5 .* tmp2
    @einsum tmp2[i,j,a,b] = H_ovov[i,c,k,a] * t1[k,b] * t1[j,c]
    R2 .+= tmp2
    @einsum tmp2[i,j,a,b] = H_ovov[i,c,k,a] * t2[j,k,b,c]
    R2 .-= tmp2
    @einsum tmp2[i,j,a,b] = H_vvov[c,d,k,a] * t1[k,b] * t2[i,j,c,d]
    R2 .+= 0.25 .* tmp2
    @einsum tmp2[i,j,a,b] = H_vvov[c,d,k,a] * t1[k,b] * t1[i,d] * t1[j,c]
    R2 .-= 0.5 .* tmp2
    @einsum tmp2[i,j,a,b] = H_vvov[c,d,k,a] * t3[i,j,k,b,c,d]
    R2 .+= 0.25 .* tmp2
    @einsum tmp2[i,j,a,b] = H_vvov[c,d,k,a] * t1[i,c] * t2[j,k,b,d]
    R2 .-= tmp2
    @einsum tmp2[i,j,a,b] = H_vvov[c,d,k,a] * t1[k,c] * t2[i,j,b,d]
    R2 .-= 0.5 .* tmp2
    @einsum tmp2[i,j,a,b] = H_vv[c,a] * t2[i,j,b,c]
    R2 .-= 0.5 .* tmp2
    R2 .+= 0.25 .* H_oovv
    @einsum tmp2[i,j,a,b] = H_ovvv[i,c,a,b] * t1[j,c]
    R2 .+= 0.5 .* tmp2
    @einsum tmp2[i,j,a,b] = H_vvvv[c,d,a,b] * t2[i,j,c,d]
    R2 .+= 0.125 .* tmp2
    @einsum tmp2[i,j,a,b] = H_vvvv[c,d,a,b] * t1[i,d] * t1[j,c]
    R2 .-= 0.25 .* tmp2

    R3 = zeros(Float64, o, o, o, v, v, v)
    tmp3 = zeros(Float64, o, o, o, v, v, v)

    @einsum tmp3[i,j,k,a,b,c] = H_oo[i,l] * t3[j,k,l,a,b,c]
    R3 .-= (1.0 / 12.0) .* tmp3
    @einsum tmp3[i,j,k,a,b,c] = H_vo[d,l] * t1[l,a] * t3[i,j,k,b,c,d]
    R3 .-= (1.0 / 12.0) .* tmp3
    @einsum tmp3[i,j,k,a,b,c] = H_vo[d,l] * t2[i,l,a,b] * t2[j,k,c,d]
    R3 .+= 0.25 .* tmp3
    @einsum tmp3[i,j,k,a,b,c] = H_vo[d,l] * t1[i,d] * t3[j,k,l,a,b,c]
    R3 .-= (1.0 / 12.0) .* tmp3
    @einsum tmp3[i,j,k,a,b,c] = H_oooo[i,j,l,m] * t1[l,a] * t2[k,m,b,c]
    R3 .-= 0.25 .* tmp3
    @einsum tmp3[i,j,k,a,b,c] = H_oooo[i,j,l,m] * t3[k,l,m,a,b,c]
    R3 .+= (1.0 / 24.0) .* tmp3
    @einsum tmp3[i,j,k,a,b,c] = H_ovoo[i,d,l,m] * t1[l,a] * t1[m,b] * t2[j,k,c,d]
    R3 .-= 0.25 .* tmp3
    @einsum tmp3[i,j,k,a,b,c] = H_ovoo[i,d,l,m] * t1[l,a] * t3[j,k,m,b,c,d]
    R3 .-= 0.25 .* tmp3
    @einsum tmp3[i,j,k,a,b,c] = H_ovoo[i,d,l,m] * t1[l,a] * t1[j,d] * t2[k,m,b,c]
    R3 .-= 0.5 .* tmp3
    @einsum tmp3[i,j,k,a,b,c] = H_ovoo[i,d,l,m] * t2[j,m,a,b] * t2[k,l,c,d]
    R3 .-= 0.5 .* tmp3
    @einsum tmp3[i,j,k,a,b,c] = H_ovoo[i,d,l,m] * t2[l,m,a,b] * t2[j,k,c,d]
    R3 .-= 0.125 .* tmp3
    @einsum tmp3[i,j,k,a,b,c] = H_ovoo[i,d,l,m] * t1[j,d] * t3[k,l,m,a,b,c]
    R3 .+= (1.0 / 12.0) .* tmp3
    @einsum tmp3[i,j,k,a,b,c] = H_ovoo[i,d,l,m] * t1[l,d] * t3[j,k,m,a,b,c]
    R3 .+= (1.0 / 12.0) .* tmp3
    @einsum tmp3[i,j,k,a,b,c] = H_vvoo[d,e,l,m] * t1[l,a] * t1[m,b] * t3[i,j,k,c,d,e]
    R3 .+= (1.0 / 24.0) .* tmp3
    @einsum tmp3[i,j,k,a,b,c] = H_vvoo[d,e,l,m] * t1[l,a] * t1[m,b] * t1[i,d] * t2[j,k,c,e]
    R3 .-= 0.25 .* tmp3
    @einsum tmp3[i,j,k,a,b,c] = H_vvoo[d,e,l,m] * t1[l,a] * t2[i,m,b,c] * t2[j,k,d,e]
    R3 .-= 0.125 .* tmp3
    @einsum tmp3[i,j,k,a,b,c] = H_vvoo[d,e,l,m] * t1[l,a] * t2[i,j,b,e] * t2[k,m,c,d]
    R3 .-= 0.5 .* tmp3
    @einsum tmp3[i,j,k,a,b,c] = H_vvoo[d,e,l,m] * t1[l,a] * t1[i,d] * t3[j,k,m,b,c,e]
    R3 .-= 0.25 .* tmp3
    @einsum tmp3[i,j,k,a,b,c] = H_vvoo[d,e,l,m] * t1[l,a] * t1[i,e] * t1[j,d] * t2[k,m,b,c]
    R3 .+= 0.25 .* tmp3
    @einsum tmp3[i,j,k,a,b,c] = H_vvoo[d,e,l,m] * t1[m,a] * t1[l,d] * t3[i,j,k,b,c,e]
    R3 .-= (1.0 / 12.0) .* tmp3
    @einsum tmp3[i,j,k,a,b,c] = H_vvoo[d,e,l,m] * t2[i,l,a,b] * t3[j,k,m,c,d,e]
    R3 .+= 0.125 .* tmp3
    @einsum tmp3[i,j,k,a,b,c] = H_vvoo[d,e,l,m] * t2[l,m,a,b] * t3[i,j,k,c,d,e]
    R3 .+= (1.0 / 48.0) .* tmp3
    @einsum tmp3[i,j,k,a,b,c] = H_vvoo[d,e,l,m] * t2[i,j,a,d] * t3[k,l,m,b,c,e]
    R3 .+= 0.125 .* tmp3
    @einsum tmp3[i,j,k,a,b,c] = H_vvoo[d,e,l,m] * t2[i,l,a,d] * t3[j,k,m,b,c,e]
    R3 .+= 0.25 .* tmp3
    @einsum tmp3[i,j,k,a,b,c] = H_vvoo[d,e,l,m] * t2[l,m,a,d] * t3[i,j,k,b,c,e]
    R3 .+= (1.0 / 24.0) .* tmp3
    @einsum tmp3[i,j,k,a,b,c] = H_vvoo[d,e,l,m] * t1[i,d] * t2[j,m,a,b] * t2[k,l,c,e]
    R3 .-= 0.5 .* tmp3
    @einsum tmp3[i,j,k,a,b,c] = H_vvoo[d,e,l,m] * t1[i,d] * t2[l,m,a,b] * t2[j,k,c,e]
    R3 .-= 0.125 .* tmp3
    @einsum tmp3[i,j,k,a,b,c] = H_vvoo[d,e,l,m] * t1[l,d] * t2[i,m,a,b] * t2[j,k,c,e]
    R3 .+= 0.25 .* tmp3
    @einsum tmp3[i,j,k,a,b,c] = H_vvoo[d,e,l,m] * t2[i,j,d,e] * t3[k,l,m,a,b,c]
    R3 .+= (1.0 / 48.0) .* tmp3
    @einsum tmp3[i,j,k,a,b,c] = H_vvoo[d,e,l,m] * t2[i,l,d,e] * t3[j,k,m,a,b,c]
    R3 .+= (1.0 / 24.0) .* tmp3
    @einsum tmp3[i,j,k,a,b,c] = H_vvoo[d,e,l,m] * t1[i,e] * t1[j,d] * t3[k,l,m,a,b,c]
    R3 .-= (1.0 / 24.0) .* tmp3
    @einsum tmp3[i,j,k,a,b,c] = H_vvoo[d,e,l,m] * t1[i,e] * t1[l,d] * t3[j,k,m,a,b,c]
    R3 .-= (1.0 / 12.0) .* tmp3
    @einsum tmp3[i,j,k,a,b,c] = H_ooov[i,j,l,a] * t2[k,l,b,c]
    R3 .-= 0.25 .* tmp3
    @einsum tmp3[i,j,k,a,b,c] = H_ovov[i,d,l,a] * t1[l,b] * t2[j,k,c,d]
    R3 .-= 0.5 .* tmp3
    @einsum tmp3[i,j,k,a,b,c] = H_ovov[i,d,l,a] * t3[j,k,l,b,c,d]
    R3 .-= 0.25 .* tmp3
    @einsum tmp3[i,j,k,a,b,c] = H_ovov[i,d,l,a] * t1[j,d] * t2[k,l,b,c]
    R3 .-= 0.5 .* tmp3
    @einsum tmp3[i,j,k,a,b,c] = H_vvov[d,e,l,a] * t1[l,b] * t3[i,j,k,c,d,e]
    R3 .+= (1.0 / 12.0) .* tmp3
    @einsum tmp3[i,j,k,a,b,c] = H_vvov[d,e,l,a] * t1[l,b] * t1[i,d] * t2[j,k,c,e]
    R3 .-= 0.5 .* tmp3
    @einsum tmp3[i,j,k,a,b,c] = H_vvov[d,e,l,a] * t2[i,l,b,c] * t2[j,k,d,e]
    R3 .-= 0.125 .* tmp3
    @einsum tmp3[i,j,k,a,b,c] = H_vvov[d,e,l,a] * t2[i,j,b,e] * t2[k,l,c,d]
    R3 .-= 0.5 .* tmp3
    @einsum tmp3[i,j,k,a,b,c] = H_vvov[d,e,l,a] * t1[i,d] * t3[j,k,l,b,c,e]
    R3 .-= 0.25 .* tmp3
    @einsum tmp3[i,j,k,a,b,c] = H_vvov[d,e,l,a] * t1[l,d] * t3[i,j,k,b,c,e]
    R3 .+= (1.0 / 12.0) .* tmp3
    @einsum tmp3[i,j,k,a,b,c] = H_vvov[d,e,l,a] * t1[i,e] * t1[j,d] * t2[k,l,b,c]
    R3 .+= 0.25 .* tmp3
    @einsum tmp3[i,j,k,a,b,c] = H_vv[d,a] * t3[i,j,k,b,c,d]
    R3 .+= (1.0 / 12.0) .* tmp3
    @einsum tmp3[i,j,k,a,b,c] = H_ovvv[i,d,a,b] * t2[j,k,c,d]
    R3 .-= 0.25 .* tmp3
    @einsum tmp3[i,j,k,a,b,c] = H_vvvv[d,e,a,b] * t3[i,j,k,c,d,e]
    R3 .+= (1.0 / 24.0) .* tmp3
    @einsum tmp3[i,j,k,a,b,c] = H_vvvv[d,e,a,b] * t1[i,d] * t2[j,k,c,e]
    R3 .-= 0.25 .* tmp3

    return (r1=R1, r2=R2, r3=R3)
end

function _combinations(values::AbstractVector, k::Integer)
    k == 0 && return [Tuple{}()]
    k > length(values) && return Tuple[]

    combos = Tuple[]
    current = Int[]
    function visit(start, remaining)
        if remaining == 0
            push!(combos, Tuple(current))
            return nothing
        end
        last_start = length(values) - remaining + 1
        for idx in start:last_start
            push!(current, values[idx])
            visit(idx + 1, remaining - 1)
            pop!(current)
        end
        return nothing
    end
    visit(1, k)
    return combos
end

"""
    cisdt_determinants(nspin, n_elec) -> (determinants, labels)

Generate reference, single, double, and triple excitations from the canonical
occupied/virtual partition:

```text
|Phi_ijk^abc> = a_a^+ a_b^+ a_c^+ a_k a_j a_i |Phi_0>.
```
"""
function cisdt_determinants(nspin::Integer, n_elec::Integer)
    base = cisd_determinants(nspin, n_elec)
    occupied = collect(1:n_elec)
    virtual = collect((n_elec + 1):nspin)
    reference = base.determinants[1]

    determinants = copy(base.determinants)
    labels = copy(base.labels)

    for holes in _combinations(occupied, 3), particles in _combinations(virtual, 3)
        det = reference
        for hole in holes
            det ⊻= _orbital_bit(hole)
        end
        for particle in particles
            det |= _orbital_bit(particle)
        end
        push!(determinants, det)
        push!(labels, (rank=3, holes=holes, particles=particles))
    end

    return (determinants=determinants, labels=labels)
end

function _apply_raw_excitation(det::CISDDet, holes, particles)
    current = det
    phase = 1.0
    for hole in holes
        step = _annihilate(current, hole)
        step.ok || return (ok=false, det=det, phase=0.0)
        current = step.det
        phase *= step.phase
    end
    for particle in reverse(particles)
        step = _create(current, particle)
        step.ok || return (ok=false, det=det, phase=0.0)
        current = step.det
        phase *= step.phase
    end
    return (ok=true, det=current, phase=phase)
end

function _reference_phases(labels, reference)
    phases = zeros(Float64, length(labels))
    phases[1] = 1.0
    for idx in 2:length(labels)
        label = labels[idx]
        applied = _apply_raw_excitation(reference, label.holes, label.particles)
        applied.ok ||
            throw(ArgumentError("Excitation label $idx cannot be applied to the reference"))
        phases[idx] = applied.phase
    end
    return phases
end

function _cluster_apply(coefficients, amplitudes, labels, determinants, det_index, reference_phases)
    result = zeros(Float64, length(coefficients))
    for (col, coefficient) in pairs(coefficients)
        coefficient == 0.0 && continue
        det = determinants[col]
        for idx in 2:length(labels)
            amplitude = amplitudes[idx]
            amplitude == 0.0 && continue
            label = labels[idx]
            applied = _apply_raw_excitation(det, label.holes, label.particles)
            applied.ok || continue
            row = get(det_index, applied.det, 0)
            row == 0 && continue
            result[row] += coefficient * amplitude * applied.phase / reference_phases[idx]
        end
    end
    return result
end

"""
    ccsdt_wavefunction_coefficients(amplitudes, labels, determinants; max_power=3)

Evaluate `exp(T1 + T2 + T3) |0>` in the CISDT determinant space.

```text
C = [1 + T + T^2/2! + T^3/3! + ...] |Phi_0>.
```
"""
function ccsdt_wavefunction_coefficients(amplitudes, labels, determinants; max_power=3)
    length(amplitudes) == length(labels) == length(determinants) ||
        throw(DimensionMismatch("Amplitude, label, and determinant counts differ"))

    det_index = Dict(det => idx for (idx, det) in pairs(determinants))
    reference_phases = _reference_phases(labels, determinants[1])
    coefficients = zeros(Float64, length(determinants))
    coefficients[1] = 1.0
    term = copy(coefficients)
    scale = 1.0
    for power in 1:max_power
        term = _cluster_apply(term, amplitudes, labels, determinants, det_index, reference_phases)
        scale *= power
        coefficients .+= term ./ scale
    end
    return coefficients
end

function _permutations_tuple(values::Tuple)
    length(values) <= 1 && return [values]
    perms = Tuple[]
    for idx in 1:length(values)
        head = values[idx]
        rest = Tuple(values[j] for j in 1:length(values) if j != idx)
        for tail in _permutations_tuple(rest)
            push!(perms, (head, tail...))
        end
    end
    return perms
end

function _permutation_sign(canonical::Tuple, permuted::Tuple)
    positions = Dict(value => idx for (idx, value) in pairs(canonical))
    order = [positions[value] for value in permuted]
    inversions = 0
    for i in 1:(length(order) - 1), j in (i + 1):length(order)
        order[i] > order[j] && (inversions += 1)
    end
    return isodd(inversions) ? -1.0 : 1.0
end

function _ccsdt_amplitude_arrays(amplitudes, labels, n_elec, nspin)
    o = n_elec
    v = nspin - n_elec
    t1 = zeros(Float64, o, v)
    t2 = zeros(Float64, o, o, v, v)
    t3 = zeros(Float64, o, o, o, v, v, v)

    for idx in 2:length(labels)
        label = labels[idx]
        amplitude = amplitudes[idx]
        if label.rank == 1
            i = label.holes[1]
            a = label.particles[1] - o
            t1[i,a] = amplitude
        elseif label.rank == 2
            holes = label.holes
            particles = Tuple(p - o for p in label.particles)
            for hp in _permutations_tuple(holes), pp in _permutations_tuple(particles)
                sign = _permutation_sign(holes, hp) * _permutation_sign(particles, pp)
                t2[hp[1], hp[2], pp[1], pp[2]] = sign * amplitude
            end
        elseif label.rank == 3
            holes = label.holes
            particles = Tuple(p - o for p in label.particles)
            for hp in _permutations_tuple(holes), pp in _permutations_tuple(particles)
                sign = _permutation_sign(holes, hp) * _permutation_sign(particles, pp)
                t3[hp[1], hp[2], hp[3], pp[1], pp[2], pp[3]] = sign * amplitude
            end
        end
    end

    return (t1=t1, t2=t2, t3=t3)
end

function _antisymmetrize_residual_2_2(R)
    return (R
            .- permutedims(R, (2, 1, 3, 4))
            .- permutedims(R, (1, 2, 4, 3))
            .+ permutedims(R, (2, 1, 4, 3)))
end

function _antisymmetrize_residual_3_3(R)
    result = zeros(Float64, size(R))
    canonical = (1, 2, 3)
    for hp in _permutations_tuple(canonical), pp in _permutations_tuple(canonical)
        sign = _permutation_sign(canonical, hp) * _permutation_sign(canonical, pp)
        result .+= sign .* permutedims(R, (hp..., (pp .+ 3)...))
    end
    return result
end

function _ccsdt_inverse_denominators(H)
    o = size(H.oo, 1)
    v = size(H.vv, 1)
    eps_occ = diag(H.oo)
    eps_vir = diag(H.vv)

    D1 = zeros(Float64, o, v)
    @threads for idx in eachindex(D1)
        x = idx - 1
        i = (x % o) + 1
        a = (x ÷ o) + 1
        @inbounds D1[i,a] = 1.0 / (eps_occ[i] - eps_vir[a])
    end

    D2 = zeros(Float64, o, o, v, v)
    @threads for idx in eachindex(D2)
        x = idx - 1
        i = (x % o) + 1; x ÷= o
        j = (x % o) + 1; x ÷= o
        a = (x % v) + 1; x ÷= v
        b = (x % v) + 1
        @inbounds D2[i,j,a,b] = 1.0 / (eps_occ[i] + eps_occ[j] - eps_vir[a] - eps_vir[b])
    end

    D3 = zeros(Float64, o, o, o, v, v, v)
    @threads for idx in eachindex(D3)
        x = idx - 1
        i = (x % o) + 1; x ÷= o
        j = (x % o) + 1; x ÷= o
        k = (x % o) + 1; x ÷= o
        a = (x % v) + 1; x ÷= v
        b = (x % v) + 1; x ÷= v
        c = (x % v) + 1
        @inbounds D3[i,j,k,a,b,c] = 1.0 / (
            eps_occ[i] + eps_occ[j] + eps_occ[k] -
            eps_vir[a] - eps_vir[b] - eps_vir[c]
        )
    end

    return (d1=D1, d2=D2, d3=D3)
end

function _initial_ccsdt_amplitudes(H, denominators)
    o = size(H.oo, 1)
    v = size(H.vv, 1)
    t1 = zeros(Float64, o, v)
    t2 = H.oovv .* denominators.d2
    t3 = zeros(Float64, o, o, o, v, v, v)
    return (t1=t1, t2=t2, t3=t3)
end

function _ccsdt_update_error(t1_new, t2_new, t3_new, t1, t2, t3)
    error = Vector{Float64}(undef, length(t1) + length(t2) + length(t3))
    offset = 0
    @inbounds for idx in eachindex(t1)
        error[offset + idx] = t1_new[idx] - t1[idx]
    end
    offset += length(t1)
    @inbounds for idx in eachindex(t2)
        error[offset + idx] = t2_new[idx] - t2[idx]
    end
    offset += length(t2)
    @inbounds for idx in eachindex(t3)
        error[offset + idx] = t3_new[idx] - t3[idx]
    end
    return error
end

function _extrapolate_ccsdt_amplitudes(amplitude_history, coefficients)
    t1_template, t2_template, t3_template = amplitude_history[end]
    t1 = zeros(Float64, size(t1_template))
    t2 = zeros(Float64, size(t2_template))
    t3 = zeros(Float64, size(t3_template))
    for (coefficient, amplitudes) in zip(coefficients, amplitude_history)
        old_t1, old_t2, old_t3 = amplitudes
        t1 .+= coefficient .* old_t1
        t2 .+= coefficient .* old_t2
        t3 .+= coefficient .* old_t3
    end
    return t1, t2, t3
end

function _ccsdt_residual_norm(r1, r2, r3)
    return sqrt(sum(abs2, r1) + sum(abs2, r2) + sum(abs2, r3))
end

"""
    ccsdt_scf(H; maxiter, e_tol, amp_tol, residual_tol, diis, verbose)

Solve the Wicked-generated CCSDT amplitude equations with Jacobi updates and
optional DIIS acceleration.
"""
function ccsdt_scf(H; maxiter=100, e_tol=1e-10, amp_tol=1e-8, residual_tol=1e-8,
                   diis=true, diis_size=8, diis_start=3, verbose=true)
    diis_size >= 2 || throw(ArgumentError("CCSDT DIIS needs diis_size >= 2"))
    diis_start >= 2 || throw(ArgumentError("CCSDT DIIS should start after at least two iterations"))

    denominators = _ccsdt_inverse_denominators(H)
    amplitudes = _initial_ccsdt_amplitudes(H, denominators)
    t1 = amplitudes.t1
    t2 = amplitudes.t2
    t3 = amplitudes.t3

    E_ccsdt = ccsdt_energy(H, t1, t2)
    amplitude_history = Tuple{Matrix{Float64}, Array{Float64,4}, Array{Float64,6}}[]
    error_history = Vector{Float64}[]
    converged = false
    iterations = maxiter
    residual_norm = Inf

    if verbose
        println("\n  CCSDT Iterations (Wicked-generated residuals):")
        println("  " * "─"^78)
        @printf("  %6s  %20s  %12s  %12s  %12s\n",
                "Iter", "E_corr", "ΔE", "‖ΔT‖", "‖R‖")
        println("  " * "─"^78)
    end

    for iteration in 1:maxiter
        residuals = ccsdt_residuals(H, t1, t2, t3)
        r1 = residuals.r1
        r2 = _antisymmetrize_residual_2_2(residuals.r2)
        r3 = _antisymmetrize_residual_3_3(residuals.r3)
        residual_norm = _ccsdt_residual_norm(r1, r2, r3)

        t1_new = t1 .+ r1 .* denominators.d1
        t2_new = t2 .+ r2 .* denominators.d2
        t3_new = t3 .+ r3 .* denominators.d3

        t1_next = t1_new
        t2_next = t2_new
        t3_next = t3_new
        if diis
            push!(error_history, _ccsdt_update_error(t1_new, t2_new, t3_new, t1, t2, t3))
            push!(amplitude_history, (copy(t1_new), copy(t2_new), copy(t3_new)))
            while length(error_history) > diis_size
                popfirst!(error_history)
                popfirst!(amplitude_history)
            end
            if iteration >= diis_start && length(error_history) >= 2
                coefficients = cc_diis_coefficients(error_history)
                t1_next, t2_next, t3_next = _extrapolate_ccsdt_amplitudes(amplitude_history, coefficients)
            end
        end

        E_new = ccsdt_energy(H, t1_next, t2_next)
        delta_E = abs(E_new - E_ccsdt)
        delta_T = maximum((
            sqrt(sum(abs2, t1_next .- t1)),
            sqrt(sum(abs2, t2_next .- t2)),
            sqrt(sum(abs2, t3_next .- t3)),
        ))

        verbose && @printf("  %6d  %20.12f  %12.4e  %12.4e  %12.4e\n",
                           iteration, E_new, delta_E, delta_T, residual_norm)

        t1 = t1_next
        t2 = t2_next
        t3 = t3_next
        E_ccsdt = E_new

        if delta_E < e_tol && delta_T < amp_tol && residual_norm < residual_tol
            converged = true
            iterations = iteration
            verbose && begin
                println("  " * "─"^78)
                @printf("  Converged in %d iterations.\n", iteration)
            end
            break
        end
    end

    converged || @warn "CCSDT did not converge in $maxiter iterations."
    return (
        E_ccsdt = E_ccsdt,
        t1 = t1,
        t2 = t2,
        t3 = t3,
        denominators = denominators,
        converged = converged,
        iterations = iterations,
        residual_norm = residual_norm,
    )
end

"""
    ci_to_ccsdt_amplitudes(ci_vector, labels, determinants, n_elec, nspin)

Convert CI coefficients through triples into connected cluster amplitudes by
recursively subtracting lower-rank disconnected contributions from
`exp(T1+T2+T3)|0>`.  For each excitation rank `r`, the connected amplitude is

```text
t_mu = C_mu/C_0 - [exp(T_lower)]_mu,
```

where `T_lower` contains amplitudes already determined at lower rank.
"""
function ci_to_ccsdt_amplitudes(ci_vector, labels, determinants, n_elec, nspin)
    length(ci_vector) == length(labels) == length(determinants) ||
        throw(DimensionMismatch("CI vector, labels, and determinants must have the same length"))

    ci = copy(Vector{Float64}(ci_vector))
    ci[1] < 0 && (ci .*= -1)
    ci ./= ci[1]

    amplitudes = zeros(Float64, length(labels))
    for rank in 1:3
        lower = ccsdt_wavefunction_coefficients(amplitudes, labels, determinants; max_power=rank)
        for idx in eachindex(labels)
            labels[idx].rank == rank || continue
            amplitudes[idx] = ci[idx] - lower[idx]
        end
    end

    cc_coefficients = ccsdt_wavefunction_coefficients(amplitudes, labels, determinants; max_power=3)
    arrays = _ccsdt_amplitude_arrays(amplitudes, labels, n_elec, nspin)
    return merge(arrays, (
        amplitudes = amplitudes,
        ci_coefficients = ci,
        cc_coefficients = cc_coefficients,
        max_coefficient_error = maximum(abs.(cc_coefficients .- ci)),
    ))
end

"""
    run_cisdt_model(rhf, mp2_result; nroots=5, verbose=true)

Build the CISDT determinant Hamiltonian and return connected `T1/T2/T3`
amplitudes obtained from the lowest root.  This is a determinant-space model
for checking cluster-amplitude bookkeeping; it solves

```text
H C = E C
```

before mapping the lowest CI vector into connected amplitudes.
"""
function run_cisdt_model(rhf, mp2_result; nroots=5, verbose=true)
    nspin = 2 * rhf.nbasis
    n_elec = rhf.n_elec
    dets = cisdt_determinants(nspin, n_elec)

    h_mo = Mat_aotoMat_mo(rhf.mo_coeffs, rhf.h1e)
    h_so = spatial_to_spinorbital_1e(h_mo)
    aso = mo_to_aso(mp2_result.new_eri)
    H = build_cisd_hamiltonian(h_so, aso, dets.determinants)

    eig = eigen(Symmetric(H))
    roots = min(nroots, length(eig.values))
    nuclear_repulsion = rhf.total_energy - rhf.energy
    total_energies = eig.values[1:roots] .+ nuclear_repulsion
    correlation_energies = total_energies .- rhf.total_energy
    cluster = ci_to_ccsdt_amplitudes(eig.vectors[:, 1], dets.labels, dets.determinants, n_elec, nspin)

    singles = count(label -> label.rank == 1, dets.labels)
    doubles = count(label -> label.rank == 2, dets.labels)
    triples = count(label -> label.rank == 3, dets.labels)
    verbose && begin
        @printf("CCSDT model dimension   = %d (%d S, %d D, %d T + reference)\n",
                length(dets.determinants), singles, doubles, triples)
        @printf("CCSDT model corr energy = %20.12f Eh\n", correlation_energies[1])
        @printf("CCSDT model total       = %20.12f Eh\n", total_energies[1])
        @printf("max |C - exp(T)|        = %12.4e\n", cluster.max_coefficient_error)
    end

    return merge(cluster, (
        E_ccsdt = correlation_energies[1],
        total_energy = total_energies[1],
        electronic_energy = eig.values[1],
        electronic_energies = eig.values[1:roots],
        total_energies = total_energies,
        correlation_energies = correlation_energies,
        ci_vector = eig.vectors[:, 1],
        ci_vectors = eig.vectors[:, 1:roots],
        reference_weight = eig.vectors[1, 1]^2,
        hamiltonian = H,
        determinants = dets.determinants,
        labels = dets.labels,
        dimension = length(dets.determinants),
        singles = singles,
        doubles = doubles,
        triples = triples,
        h_so = h_so,
        aso = aso,
    ))
end

"""
    run_ccsdt(rhf, mp2_result; maxiter=100, diis=true, verbose=true)

Run full spin-orbital CCSDT using the Wicked-generated residual equations.
Jacobi iterations use orbital-energy denominators,

```text
t_mu <- t_mu + R_mu / D_mu,
```

with optional DIIS extrapolation of the amplitude vectors.
"""
function run_ccsdt(rhf, mp2_result;
                   maxiter=100, e_tol=1e-10, amp_tol=1e-8, residual_tol=1e-8,
                   diis=true, diis_size=8, diis_start=3, verbose=true)
    n_elec = rhf.n_elec
    o = n_elec
    v = 2 * rhf.nbasis - n_elec

    aso = mo_to_aso(mp2_result.new_eri)
    F_so = Mat_motoMat_so(Mat_aotoMat_mo(rhf.mo_coeffs, rhf.fock))
    H = _ccsdt_hamiltonian_blocks(aso, F_so, o, v, n_elec)

    result = ccsdt_scf(H; maxiter, e_tol, amp_tol, residual_tol,
                       diis, diis_size, diis_start, verbose)
    total = rhf.total_energy + result.E_ccsdt
    if verbose
        @printf("\nCCSDT correlation energy = %20.12f Eh\n", result.E_ccsdt)
        @printf("CCSDT total energy       = %20.12f Eh\n", total)
    end

    return merge(result, (
        total_energy = total,
        aso = aso,
        hamiltonian_blocks = H,
        wicked_terms = (energy=3, singles=15, doubles=37, triples=47),
    ))
end
